# Generated by Django 4.1.3 on 2022-12-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_schedule_quote_scheduling_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_tag',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='scheduling_time',
        ),
        migrations.AddField(
            model_name='quote',
            name='scheduling_time',
            field=models.DateTimeField(null=True, verbose_name='message time'),
        ),
    ]
