# Generated by Django 4.1.3 on 2022-12-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_schedule_time_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
