# Generated by Django 4.1.4 on 2022-12-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_remove_quote_scheduling_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
