# Generated by Django 4.1.4 on 2022-12-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_alter_quote_date_alter_quote_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
