# Generated by Django 4.1.4 on 2022-12-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_alter_quote_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
