# Generated by Django 4.1.4 on 2022-12-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_alter_quote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
