# Generated by Django 4.1.4 on 2022-12-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_quote_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='date_time',
        ),
    ]
