# Generated by Django 4.1.4 on 2023-01-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_rename_time_quote_date_time_remove_quote_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date_time',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
