# Generated by Django 4.1.4 on 2023-01-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_alter_quote_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
