# Generated by Django 4.1.4 on 2023-01-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_quote_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='format_time_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
