# Generated by Django 4.1.4 on 2023-01-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
