# Generated by Django 4.1.4 on 2023-01-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_phone_number_alter_phone_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='dev_images/default_profile_img.svg', null=True, upload_to='images/'),
        ),
    ]
